version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run: node --version
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in both apps
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: main
